// Generated by CoffeeScript 1.7.0
define(['marionette'], function(Marionette) {
  var ComposeView, View;
  ComposeView = Marionette.ItemView.extend({
    template: jade.templates['compose'],
    events: {
      'click .do-sendmail': 'sendMail'
    },
    initialize: function() {
      console.log('Compose Render');
      return $(".do-sendmail").removeClass('hidden');
    },
    sendMail: function() {
      var obj;
      obj = {};
      obj.to = this.$el.find('#toaddress');
      obj.from = 'nanuclickity';
      obj.text = this.$el.find('#text');
      obj.subject = this.$el.find('#tosubject');
      return $.post('/send', obj, function(response) {
        console.log('Sending... ');
        console.log('This is the response...');
        return console.log(response);
      });
    }
  });
  View = new ComposeView();
  return View;
});
