// Generated by CoffeeScript 1.7.0
define(['marionette'], function(Marionette) {
  var ComposeView, View;
  ComposeView = Marionette.ItemView.extend({
    template: jade.templates['compose'],
    events: {
      'click .do-sendmail': 'sendMail'
    },
    initialize: function() {
      return console.log('Compose Render');
    },
    sendMail: function() {
      var obj;
      obj = {};
      obj.to = this.$el.find('#toaddress');
      obj.text = this.$el.find('#text');
      obj.subject = this.$el.find('#tosubject');
      return console.log(obj);
    }
  });
  View = new ComposeView();
  return View;
});
