// Generated by CoffeeScript 1.7.0
define(['marionette', 'vent'], function(Marionette, vent) {
  var HeaderView, View;
  HeaderView = Marionette.ItemView.extend({
    template: jade.templates['header'],
    tagName: 'header',
    className: 'header-inner',
    events: {
      'click .do-showMenu': 'showMenu',
      'click .do-renderInbox': 'goInbox'
    },
    goInbox: function() {
      var element;
      console.log('YoYo');
      element = $(".user-info .message.fullmode");
      console.log(element);
      $(element).parent().parent().find('.user-info .short-message').toggle();
      $(element).hide().addClass('hidden').removeClass('fullmode');
      return vent.trigger('header:update:name', 'Inbox');
    },
    showMenu: function() {
      return vent.trigger('menu:show');
    },
    updateName: function(_name) {
      return this.$el.find('.panel-name').text(_name);
    }
  });
  View = new HeaderView();
  vent.on('header:update:name', function(name) {
    return View.updateName(name);
  });
  return View;
});
