// Generated by CoffeeScript 1.7.0
define(['marionette'], function(Marionette) {
  var HomeView, View;
  HomeView = Marionette.ItemView.extend({
    template: jade.templates['home'],
    events: {
      'click .login-button': 'doLogin'
    },
    doLogin: function() {
      var ppass, uname;
      uname = this.$el.find('#username').val();
      ppass = this.$el.find('#password').val();
      return $.post('/login', {
        username: uname,
        password: ppass
      }, function(response) {
        if (response === 'OK') {
          return Backbone.history.navigate('inbox', {
            trigger: true
          });
        } else {
          return Backbone.history.navigate('register', {
            trigger: true
          });
        }
      });
    },
    onRender: function() {
      this.$el.attr('data-fullwidth', 'true');
      return $.getJSON('/debug', function(data) {
        if (data.username != null) {
          console.log('Already logged in... Proceeding.');
          return Backbone.history.navigate('inbox', {
            trigger: true
          });
        } else {
          return console.error('Login is mandatory');
        }
      });
    }
  });
  View = new HomeView();
  return View;
});
