// Generated by CoffeeScript 1.7.0
define(['marionette', 'controllers/content', 'vent'], function(Marionette, ContentController, vent) {
  var AppController, Controller;
  AppController = Marionette.Controller.extend({
    renderHome: function() {
      ContentController.renderView('views/home');
      return vent.trigger('header:update:name', 'Home');
    },
    renderInbox: function() {
      ContentController.renderView('views/inbox');
      return vent.trigger('header:update:name', 'Inbox');
    },
    renderEmail: function() {
      ContentController.renderView('views/inbox');
      return vent.trigger('header:update:name', 'Inbox');
    },
    renderRegister: function() {
      ContentController.renderView('views/register');
      return vent.trigger('header:update:name', 'Register');
    }
  });
  Controller = new AppController();
  return Controller;
});
