// Generated by CoffeeScript 1.7.0
define(['marionette', 'vent'], function(Marionette, vent) {
  var Controller, MenuController;
  MenuController = Marionette.Controller.extend({
    getRouteName: function(path) {
      var all_spaces;
      all_spaces = new RegExp(' ', 'g');
      return path.toLowerCase().replace(all_spaces, '');
    },
    renderMenu: function(model) {
      var name;
      name = this.getRouteName(model.get('name'));
      Backbone.history.navigate(name, {
        trigger: true
      });
      return vent.trigger('update:breadcrumbs', name);
    }
  });
  Controller = new MenuController();
  return Controller;
});
