// Generated by CoffeeScript 1.7.0
requirejs.config({
  baseUrl: './js/',
  paths: {
    jquery: './libs/jquery',
    jqueryui: './libs/jquery-ui',
    bootstrap: './libs/bootstrap',
    underscore: './libs/underscore',
    backbone: './libs/backbone',
    marionette: './libs/backbone.marionette',
    templates: './templates',
    app: './app',
    vent: './utils/vent'
  },
  shim: {
    jquery: {
      exports: 'jQuery'
    },
    jqueryui: {
      deps: ['jquery']
    },
    bootstrap: {
      deps: ['jquery']
    },
    underscore: {
      exports: '_'
    },
    templates: {
      exports: 'jade'
    },
    backbone: {
      deps: ['jquery', 'underscore'],
      exports: 'Backbone'
    },
    marionette: {
      deps: ['underscore', 'jquery', 'backbone'],
      exports: 'Marionette'
    },
    app: {
      deps: ['marionette', 'jqueryui', 'bootstrap'],
      exports: 'App'
    }
  }
});

requirejs(['app', 'templates'], function(App, jade) {
  Marionette.Renderer.render = function(tpl, data) {
    var tplFn;
    if (typeof tpl === 'function') {
      tplFn = tpl;
    } else {
      tplFn = jade.templates[tpl];
    }
    return tplFn(data);
  };
  return App.start();
});
