// Generated by CoffeeScript 1.7.0
define(['backbone'], function(Backbone) {
  var Model;
  Model = Backbone.Model.extend({
    defaults: {
      headerTitle: 'LetterSafe'
    }
  });
  return new Model;
});
