// Generated by CoffeeScript 1.7.0
define(['backbone'], function(Backbone) {
  var Model;
  Model = Backbone.Model.extend({
    defaults: {
      name: 'Sample Menu Item',
      iconClass: 'fa fa-fw fa-music',
      hasSubMenu: false,
      isActive: false
    }
  });
  return Model;
});
