// Generated by CoffeeScript 1.7.0
define(['marionette', 'vent'], function(Marionette, vent) {
  var ContentRegion, Region;
  ContentRegion = Marionette.Region.extend({
    open: function(view) {
      view.$el.hide();
      view.$el.addClass('container-fluid');
      this.$el.html(view.el);
      return view.$el.show('drop', {
        direction: 'up'
      }, 300);
    }
  });
  Region = new ContentRegion({
    el: 'section.app-content'
  });
  vent.on('content:showview', function(view) {
    return Region.show(view);
  });
  return Region;
});
