// Generated by CoffeeScript 1.7.0
define(['marionette', 'views/header'], function(Marionette, headerView) {
  var HeaderRegion, Region;
  HeaderRegion = Marionette.Region.extend({
    open: function(view) {
      view.$el.hide();
      this.$el.html(view.el);
      return view.$el.show('drop', {
        direction: 'up'
      }, 200);
    }
  });
  Region = new HeaderRegion({
    el: 'section.app-header'
  });
  Region.show(headerView);
  return Region;
});
