// Generated by CoffeeScript 1.7.0
define(['marionette', 'vent', 'views/menu'], function(Marionette, vent, menuView) {
  var MenuRegion, Region;
  MenuRegion = Marionette.Region.extend({
    open: function(view) {
      view.$el.hide();
      this.$el.html(view.el);
      view.$el.show('drop', {
        direction: 'down'
      });
      return this;
    },
    showMenu: function() {
      this.$el.attr('data-visibility', 'visible');
      return this;
    },
    hideMenu: function() {
      this.$el.attr('data-visibility', 'hidden');
      return this;
    }
  });
  Region = new MenuRegion({
    el: 'section.app-menu'
  });
  Region.show(menuView);
  vent.on('menu:hide', function() {
    console.log('Hiding Menu');
    return Region.hideMenu();
  });
  vent.on('menu:show', function() {
    return Region.showMenu();
  });
  return Region;
});
